// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Subscribe
	Publish
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Subscribe struct {
	Topic      string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Subscriber string `protobuf:"bytes,2,opt,name=subscriber" json:"subscriber,omitempty"`
}

func (m *Subscribe) Reset()                    { *m = Subscribe{} }
func (m *Subscribe) String() string            { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()               {}
func (*Subscribe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Subscribe) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Subscribe) GetSubscriber() string {
	if m != nil {
		return m.Subscriber
	}
	return ""
}

type Publish struct {
	Topic   string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Publish) Reset()                    { *m = Publish{} }
func (m *Publish) String() string            { return proto.CompactTextString(m) }
func (*Publish) ProtoMessage()               {}
func (*Publish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Publish) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Publish) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Subscribe)(nil), "Subscribe")
	proto.RegisterType((*Publish)(nil), "Publish")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe4, 0xe2, 0x0c, 0x2e, 0x4d,
	0x2a, 0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2f, 0xc8, 0x4c, 0x96,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xe4, 0xb8, 0xb8, 0x8a, 0x61, 0x4a, 0x8a,
	0x24, 0x98, 0xc0, 0x52, 0x48, 0x22, 0x4a, 0x96, 0x5c, 0xec, 0x01, 0xa5, 0x49, 0x39, 0x99, 0xc5,
	0x19, 0x38, 0x0c, 0x90, 0xe0, 0x62, 0x87, 0x5a, 0x0a, 0xd6, 0xcd, 0x13, 0x04, 0xe3, 0x26, 0xb1,
	0x81, 0x1d, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x19, 0x21, 0xc7, 0x21, 0x95, 0x00, 0x00,
	0x00,
}
